# Inputs:
#
# Workflow:
#   - Create new domain controller
#   - Create new Failover Cluster using N nodes
#   - Run current execution plan once on any domain controller node 
#
# Notes:
#   - This script runs on one node only (Availability Group Primary node)

Scripts:
  - ../../WindowsPowerShell/Functions/ImportCoreFunctions.ps1
  - ../../WindowsPowerShell/Functions/SQLServerForAOAG.ps1
  - ../../WindowsPowerShell/Functions/New-SqlServerSystemAccount.ps1

Commands:
  - Name: Install-SqlServerPowerShellModule
    Arguments: {}

  - Name: Disable-Firewall
    Arguments: {}

  - Name: New-SqlServerSystemAccount
    Arguments:
      # [String] (REQUIRED) Domain Name
      DomainName: $domainName
      # [String] (REQUIRED) User name who has permissions to create and modify userPassword
      # Usually this is the domain administrator '$domainName\Administrator' account
      UserName: $userName
      # [String] (REQUIRED) Password for that user
      UserPassword: $userPassword
      # [String] (REQUIRED) User name for a new account that will be used to run SQL Server
      SQLServiceUserName: $sqlServiceUserName
      # [String] (REQUIRED) Password for that user
      SQLServiceUserPassword: $sqlServiceUserPassword
      # Name of the AOAG primary node
      PrimaryNode: $primaryNode

  - Name: New-SharedFolderForAOAG
    Arguments:
      # Name of the AOAG primary node
      PrimaryNode: $primaryNode
